name: Node.js CI

on:
  push:
    branches: ["main"]

  repository_dispatch:
    types: [sanity]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.11.1]

    env:
      NEXT_PUBLIC_RESEND_API_KEY: ${{secrets.NEXT_PUBLIC_RESEND_API_KEY}}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      # - name: Change Directory
      #   run: cd /home/olamide/actions-runner/_work/arise-business-club-website/arise-business-club-website
      # - run: pm2 restart 0
